Repository opensearch-project/opensearch-benchmark-workloads, pull requests merged in 2024-07, with the labels that each got.

#334 Adding new aoss vector search param fields `target_throughput`, `repetitions` and `time_period`
  vectorsearch/README.md
  vectorsearch/test_procedures/aoss/search-only-schedule.json
Labels: backport 2, backport 1, backport 3

#336 Updated recommendations in big5 README
  big5/README.md
Labels: backport 2, backport 1, backport 3, backport 7

#340 For Semantic search on NOAA increasing number of search clients to 8
  noaa_semantic_search/params/one_replica_no_concurrent_segment_search.json
  noaa_semantic_search/params/one_replica_with_concurrent_segment_search.json
Labels: backport 2, backport 1, backport 3

#333 Add vectorsearch training workload
  vectorsearch/README.md
  vectorsearch/indices/train-index.json
  vectorsearch/operations/default.json
  vectorsearch/params/train/train-faiss-sift-128-l2-pq.json
  vectorsearch/params/train/train-faiss-sift-128-l2-sq.json
  vectorsearch/params/train/train-faiss-sift-128-l2.json
  vectorsearch/test_procedures/common/train-index-only-schedule.json
  vectorsearch/test_procedures/common/train-model-schedule.json
  vectorsearch/test_procedures/default.json
  vectorsearch/workload.json
Labels: backport 2, backport 3

#350 Fix IT bug
  vectorsearch/indices/train-index.json
  vectorsearch/test_procedures/common/train-model-schedule.json
  vectorsearch/workload.json
Labels: backport 2, backport 3

#232 Add vector search with embedding generation workload
  treccovid_semantic_search/README.md
  treccovid_semantic_search/files.txt
  treccovid_semantic_search/index.json
  treccovid_semantic_search/operations/default.json
  treccovid_semantic_search/test_procedures/default.json
  treccovid_semantic_search/workload.json
  treccovid_semantic_search/workload.py
  treccovid_semantic_search/workload_queries.json
Labels: backport 2, backport 3
