Repository opensearch-project/opensearch-benchmark-workloads, pull requests merged in 2024-03, with the labels that each got.

#226 Update default param values
  vectorsearch/params/corpus/10million/faiss-cohere-768-dp.json
  vectorsearch/params/corpus/10million/lucene-cohere-768-dp.json
  vectorsearch/params/corpus/10million/nmslib-cohere-768-dp.json
  vectorsearch/params/corpus/1million/faiss-cohere-768-dp.json
  vectorsearch/params/corpus/1million/lucene-cohere-768-dp.json
  vectorsearch/params/corpus/1million/nmslib-cohere-768-dp.json
  vectorsearch/params/faiss-sift-128-l2.json
  vectorsearch/params/lucene-sift-128-l2.json
  vectorsearch/params/nmslib-sift-128-l2.json
Labels: backport 2, backport 1, backport 3

#233 Add Rishabh Singh as Maintainer after vote
  .github/CODEOWNERS
  MAINTAINERS.md
Labels: ES 6, ES 7, backport 2, backport 1, backport 3

#230 Add procedures to split indexing, search and merge
  vectorsearch/README.md
  vectorsearch/test_procedures/common/force-merge-schedule.json
  vectorsearch/test_procedures/common/index-only-schedule.json
  vectorsearch/test_procedures/common/search-only-schedule.json
  vectorsearch/test_procedures/default.json
Labels: backport 2, backport 1, backport 3

#242 Added a 100 GB corpus to the big5 workload that models a more realistic time series and updated mappings
  big5/README.md
  big5/index.json
  big5/test_procedures/common/big5-schedule.json
  big5/workload.json
Labels: backport 2, backport 1, backport 3

#247 Fix merge policy to restrict to OS 2.11+ in Big5 workload
  big5/index.json
Labels: backport 2, backport 1, backport 3, backport 7

#249 Update param values and add new procedure
  vectorsearch/params/corpus/10million/faiss-cohere-768-dp.json
  vectorsearch/params/corpus/10million/lucene-cohere-768-dp.json
  vectorsearch/params/corpus/10million/nmslib-cohere-768-dp.json
  vectorsearch/params/corpus/1million/faiss-cohere-768-dp.json
  vectorsearch/params/corpus/1million/lucene-cohere-768-dp.json
  vectorsearch/params/corpus/1million/nmslib-cohere-768-dp.json
  vectorsearch/test_procedures/default.json
Labels: backport 2, backport 1
