Repository opensearch-project/opensearch-benchmark-workloads, pull requests merged in 2024-08, with the labels that each got.

#309 Add workloads for vector radial search
  vectorsearch/README.md
  vectorsearch/_tools/add_radial_threshold_to_dataset.py
  vectorsearch/params/radial_search/faiss-hnsw-cohere-768-1m-inner-product.json
  vectorsearch/params/radial_search/lucene-hnsw-cohere-768-1m-inner-product.json
  vectorsearch/test_procedures/common/search-only-schedule.json
Labels: backport 2, backport 3

#371 add configurable throughput and client parameters
  nyc_taxis/test_procedures/default.json
Labels: backport 2, backport 1, backport 3, backport 7

#368 Add standard value sources to nyc_taxis to allow using range query randomization
  nyc_taxis/workload.py
Labels: backport 2, backport 1, backport 3
