Repository opensearch-project/opensearch-benchmark-workloads, pull requests merged in 2024-02, with the labels that each got.

#174 Update test procedure to accept search_clients
  vectorsearch/README.md
  vectorsearch/test_procedures/default.json
Labels: backport 2, backport 1, backport 3

#176 Add maintainers after OSCI Autumn 2023
  MAINTAINERS.md
Labels: ES 6, ES 7, backport 2, backport 1, backport 3

#184 Add new maintainers to .github/CODEOWNERS
  .github/CODEOWNERS
Labels: ES 6, ES 7, backport 2, backport 1, backport 3

#185 Include client processing time start and end
  vectorsearch/runners.py
Labels: backport 2, backport 1, backport 3

#193 Add neighbors to test procedure
  vectorsearch/params/nmslib-sift-128-l2.json
  vectorsearch/test_procedures/default.json
Labels: backport 2, backport 1, backport 3

#199 Update the big5 workload with specifications for the associated data corpus
  big5/README.md
  big5/index.json
  big5/operations/default.json
  big5/test_procedures/common/big5-schedule.json
  big5/workload.json
Labels: backport 2, backport 3

#202 Add query optimization to prod-queries
  vectorsearch/params/faiss-sift-128-l2.json
  vectorsearch/params/lucene-sift-128-l2.json
  vectorsearch/params/nmslib-sift-128-l2.json
  vectorsearch/test_procedures/default.json
Labels: backport 2, backport 1, backport 3
