Repository opensearch-project/opensearch-benchmark-workloads, pull requests merged in 2024-11, with the labels that each got.

#457 add configurables to noaa workload
  noaa/test_procedures/default.json
Labels: backport 1, backport 3, backport 7

#455 add configurable iterations + warmup iterations to the percolator workload
  percolator/test_procedures/default.json
Labels: backport 1, backport 3, backport 7

#449 add configurable warmup + iterations to geonames workload
  geonames/test_procedures/default.json
Labels: backport 2, backport 1, backport 3, backport 7

#448 add configurable warmup iterations + iterations to http_logs workload
  http_logs/test_procedures/default.json
Labels: backport 2, backport 1, backport 3, backport 7

#483 Add compression level param to mapping
  vectorsearch/indices/faiss-index.json
Labels: backport 2, backport 3

#498 Add configurable parameters to geonames operations
  geonames/test_procedures/default.json
Labels: backport 2, backport 1, backport 7

#499 rename params with default operation names in http-logs
  http_logs/test_procedures/default.json
Labels: backport 2, backport 1, backport 3, backport 7

#504 Add clients from geonames branch 7 to other branches
  geonames/test_procedures/default.json
Labels: backport 2, backport 1

#509 Fix geonames caused by jinja2 templating
  geonames/test_procedures/default.json
Labels: backport 2, backport 1, backport 7
