Repository opensearch-project/opensearch-benchmark-workloads, pull requests merged in 2024-10, with the labels that each got.

#426 add configurable throughput + client parameters to the pmc workload
  pmc/test_procedures/default.json
  pmc/test_procedures/indexing-querying.json
Labels: backport 2, backport 1, backport 3, backport 7

#424 add configurable throughput + client params to geopoint, geopointshape, geopoint workloads
  geopoint/test_procedures/default.json
  geopointshape/test_procedures/default.json
  geoshape/test_procedures/default.json
Labels: backport 2, backport 1, backport 3, backport 7

#423 update geonames with configurable throughput + client parameters
  geonames/test_procedures/default.json
Labels: backport 2, backport 1, backport 3, backport 7

#422 add configurable throughput + client params to http logs
  http_logs/test_procedures/default.json
Labels: backport 2, backport 1, backport 3, backport 7

#425 Add Contributor Guidelines, User Guide, and Pull Request Template
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  USER_GUIDE.md
Labels: ES 6, backport 2, backport 1, backport 3, backport 7

#451 On-boarding Disk-based-Vector on Nightly runs
  vectorsearch/indices/faiss-index.json
  vectorsearch/params/corpus/10million/faiss-cohere-768-disk-based-vector.json
Labels: OS 2, backport 2, backport 3

#456 Updated big5 to support the full 1 TiB corpus
  big5/README.md
  big5/workload.json
Labels: backport 2, backport 1, backport 3, backport 7

#458 add configurable options to nested workload
  nested/test_procedures/default.json
Labels: backport 1, backport 3, backport 7

#452 add configurable iterations + warmup iterations to the pmc workload
  pmc/test_procedures/default.json
Labels: backport 2, backport 1, backport 3, backport 7

#447 add configurable iterations to nyc_taxis workload
  nyc_taxis/test_procedures/default.json
Labels: backport 2, backport 1, backport 3, backport 7
