Repository opensearch-project/opensearch-benchmark-workloads, pull requests merged in 2024-06, with the labels that each got.

#299 [README] Add contribution guide reference to README #293
  README.md
Labels: backport 2, backport 1, backport 3, backport 7

#312 Add missing quotes to _big5_ Jinja template
  big5/README.md
  big5/workload.json
Labels: backport 2, backport 1, backport 3, backport 7

#319 Semantic search NOAA workload - move params to files, cleanup redandant operations
  noaa_semantic_search/README.md
  noaa_semantic_search/operations/hybrid_search.json
  noaa_semantic_search/params/one_replica_no_concurrent_segment_search.json
  noaa_semantic_search/params/one_replica_with_concurrent_segment_search.json
  noaa_semantic_search/test_procedures/semantic-search-common/multiple-subqueries-search.json
  noaa_semantic_search/test_procedures/semantic-search-common/profiler-workflow.json
  noaa_semantic_search/test_procedures/semantic-search-common/single-subquery-large-set-search.json
  noaa_semantic_search/test_procedures/semantic-search-common/single-subquery-medium-set-search.json
  noaa_semantic_search/test_procedures/semantic-search-common/single-subquery-small-set-search.json
Labels: backport 2, backport 3

#310 add range agg in noaa and big5 workloads
  big5/operations/default.json
  big5/test_procedures/common/big5-schedule.json
  noaa/operations/default.json
  noaa/test_procedures/default.json
Labels: backport 2, backport 1, backport 3

#311 Add cardinality aggregation in big5
  big5/operations/default.json
  big5/test_procedures/common/big5-schedule.json
Labels: backport 2, backport 1, backport 3
