Repository opensearch-project/opensearch-benchmark-workloads, pull requests merged in 2025-03, with the labels that each got.

#577 insert index_name in common operations/cluster health operations in workload schedules
  big5/test_procedures/common/big5-schedule.json
  big5/test_procedures/default.json
  eventdata/test_procedures/default.json
  geonames/test_procedures/default.json
  geopoint/test_procedures/default.json
  geopointshape/test_procedures/default.json
  geoshape/test_procedures/default.json
  http_logs/test_procedures/default.json
  nested/test_procedures/default.json
  noaa/test_procedures/default.json
  nyc_taxis/test_procedures/default.json
  percolator/test_procedures/default.json
  pmc/test_procedures/default.json
  so/test_procedures/default.json
  treccovid_semantic_search/test_procedures/default.json
Labels: backport 2, backport 1, backport 3, backport 7

#580 Update big5 to support pre-OpenSearch versions (ES 6.8, 7.10, etc.)
  big5/index.json
  big5/operations/default.json
  big5/workload.json
Labels: backport 2, backport 1, backport 3, backport 7, backport 6

#565 Adding search load for hybrid query with sort
  noaa_semantic_search/README.md
  noaa_semantic_search/operations/hybrid_search_sorting.json
  noaa_semantic_search/test_procedures/hybrid_search.json
  noaa_semantic_search/test_procedures/semantic-search-common/search-with-sort.json
Labels: backport 2, backport 3

#573 Add vector derived source setting to benchmarks
  vectorsearch/README.md
  vectorsearch/indices/faiss-index.json
  vectorsearch/indices/filters/faiss-index-attributes.json
  vectorsearch/indices/filters/lucene-index-attributes.json
  vectorsearch/indices/filters/nmslib-index-attributes.json
  vectorsearch/indices/lucene-index.json
  vectorsearch/indices/nested/nested-faiss-index.json
  vectorsearch/indices/nested/nested-lucene-index.json
  vectorsearch/indices/nested/nested-nmslib-index.json
  vectorsearch/indices/nmslib-index.json
Labels: backport 2, backport 3
